### ISSUE TITLE
能否支持获取题目的所属类别

### ISSUE THREAD

**Issue by MuYunyun** [beizhedenglong/leetcode-site-generator#10]
在 operationName 为 `questionData` 的 graph 接口中(该 graph 接口可以在 [link](https://leetcode-cn.com/problems/add-two-numbers/) 中找到), topicTags(题目类别) 这个字段比较有用能不能把它也输出来呢?

![image](https://user-images.githubusercontent.com/19354791/93967190-3e950a80-fd99-11ea-81a3-eb23251c583e.png)

我试了下在 `leetcode.js` 文件中书写 graph 接口方法获取 topicTags 字段,

```js
const getQuestionData = async (titleSlug) => {
  const qglRequest = await createGqlRequest();
  // interface from 'https://leetcode-cn.com/problems/add-two-numbers/'
  const json = await qglRequest(`{
    questionData($titleSlug: "${titleSlug}"){
      question{
        topicTags
      }
    }
  }`);
  const question = (json.questionData && json.questionData.question) || {};
  return question;
};
```

调用后, 它报 CSRF 校验失败。

![image](https://user-images.githubusercontent.com/19354791/93967316-84ea6980-fd99-11ea-8b62-0c689c91e42e.png)

大佬有什么好的思路呢? 感谢。

**Comment by beizhedenglong** [comment]
你写的 graphql 语法不对，试试这个

```js
qglRequest(`
    {
      question(titleSlug: "flatten-a-multilevel-doubly-linked-list") {
        questionId
        questionFrontendId
        status
        topicTags {
          name
          slug
        }
      }
    }
  `)
```

**Comment by MuYunyun** [comment]
@beizhedenglong 可以了。非常感谢！
