### ISSUE TITLE
Login failure, retry ...

### ISSUE THREAD

**Issue by fabiantorrestech** [beizhedenglong/leetcode-site-generator#5]
Hi, I am running `yarn download` in the leetcode-site-base/website folder, but I keep getting `Login failure, retry ...`

I normally login to leetcode using the facebook sign in method, will this still work? 

Here is what I've tried:
1) Resetting my Leetcode Password
2) Changing my Leetcode primary email

Neither seem to work. Am I missing something?

Node js version: 13.12.0
Yarn version: 1.22.4

**Comment by raghav4** [comment]
@beizhedenglong same issue :(

**Comment by beizhedenglong** [comment]
I will fix this issue this weekend!!!

**Comment by beizhedenglong** [comment]
This issue has been fixed. Please upgrade `leetcode-site-generator`: `yarn global add leetcode-site-generator@latest`

**Comment by raghav4** [comment]
Thank you so much @beizhedenglong, can't wait to use it! You've done an amazing job. Many people would want anything of this kind.  😄

**Comment by raghav4** [comment]
Hi @beizhedenglong, I think there's some change with leetcode API. I tried running the application as suggested by you. But it got crashed because of an unhandled promise rejection. While it was 90% of the completion time. Thank you though for such an amazing project!

**Comment by beizhedenglong** [comment]
Because Leetcode API has a rate limit. it will be failed sometimes.

**Comment by raghav4** [comment]
Oh, okay! I'll try it some another time again! Thank you! 😄

**Comment by beizhedenglong** [comment]
yarn can run `npm run generate-docs` to generate docs of downloaded problems. I will add a feature that will only download new submitted problems by default not all problems every time.

**Comment by raghav4** [comment]
Wow sounds great! @beizhedenglong, you're awesome. Thank you so much! 😄 🎉, I'll definitely share this project with my friends using leetcode.

**Comment by raghav4** [comment]
Btw, is there any API to get the notes one has written over the platform (leetcode)?
