### ISSUE TITLE
Could it support leetcode-cn.com?

### ISSUE THREAD

**Issue by MuYunyun** [beizhedenglong/leetcode-site-generator#8]
I try to change the code [there](https://github.com/beizhedenglong/leetcode-site-generator/blob/master/src/leetcode.js#L13-L28)

```js
const baseUrl = 'https://leetcode-cn.com';
const graphqlUrl = `${baseUrl}/graphql`;

const login = async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://leetcode-cn.com/accounts/login/');
  await page.waitForNavigation({
    timeout: 0,
  });
  const cookies = await page.cookies();
  await browser.close();
  return cookies.reduce((acc, cookie) => {
    const { name } = cookie;
    acc[name] = cookie;
    return acc;
  }, {});
};
```

then I run yarn download, and I print account and secret in puppeteer browser, it throws with ‘验证失败’

* ![image](https://user-images.githubusercontent.com/19354791/93668206-ab6c8400-fabd-11ea-98d7-20a57a531337.png)
*  ![image](https://user-images.githubusercontent.com/19354791/93668310-2b92e980-fabe-11ea-9006-ad787cc99de3.png)

Is there any way to solve it, thanks!

**Comment by beizhedenglong** [comment]
现在还不支持中文站点，我试了在 puppeteer 里面通过微信是可以登陆成功的，但是中文站点的接口和英文站点的一些接口还不一样，你想用的话，获取提交代码的接口要改一下

**Comment by MuYunyun** [comment]
@beizhedenglong 稍微调整了下 login 逻辑, 目前通过微信的登录方式登录后, 能进入后续逻辑。(github 登入方式不行, 其它登入方式没有验证过)

```js
const login = async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://leetcode-cn.com/accounts/login/');
  // only wechat login way now
  // it's to jump to the QR scan page.
  await page.waitForNavigation({
    timeout: 0,
  });
  // it's to jump to detail page.
  await page.waitForNavigation({
    timeout: 0,
  });
  const cookies = await page.cookies();
  await browser.close();
  return cookies.reduce((acc, cookie) => {
    const { name } = cookie;
    acc[name] = cookie;
    return acc;
  }, {});
};
```

**Comment by beizhedenglong** [comment]
@MuYunyun 老哥还没睡么，我晚上加了 leetcode-cn 的支持，支持全部的登陆方式!

**Comment by beizhedenglong** [comment]
发布了，更新下 `yarn global add leetcode-site-generator@latest`

**Comment by MuYunyun** [comment]
可以登录了, 大佬厉害！

另外有个小建议, 执行 download 的获取 ac 题目的时候是否能只拉取增量的数据😬

**Comment by beizhedenglong** [comment]
默认就是拉的增量数据，第一次下载拉的是全量数据
